apiVersion: v1
kind: Service
metadata:
  name: teams-bot
  namespace: default
spec:
  selector:
    app: teams-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3978
  type: ClusterIP
